### ISSUE TITLE
Lemmy from scratch install instructions fail with "thread ‘main’ panicked at ‘Couldn’t run DB Migrations’, crates/db_schema/src/utils.rs:165:25"

### ISSUE THREAD

**Issue by RocketDerp** [LemmyNet/lemmy-docs#201] opened 2023-06-09 16:43 UTC
As a workaround, before starting the lemmy server:

`sudo -iu postgres psql -c “ALTER USER lemmy WITH SUPERUSER;”`

It seems that the problematic SQL has been identified in this pull request?

https://github.com/LemmyNet/lemmy/pull/2983/commits/29c4144e61e97e895fb7eb37d2c257c8520fd6a6

**Comment by dessalines** [comment] 2023-06-09 17:03
Could you do a PR to add that to the docs?

**Comment by sunaurus** [comment] 2023-06-10 16:14
Adding superuser privileges is not an ideal solution - it means that Lemmy won't work on any managed cloud database which prevents superuser access. This PR seems like a better solution: https://github.com/LemmyNet/lemmy/pull/3002

**Comment by sunaurus** [comment] 2023-06-14 12:17
FYI as https://github.com/LemmyNet/lemmy/pull/3002 was merged, I believe this issue can be closed

**Comment by ffolkes** [comment] 2023-06-14 13:43
This is not working for me, and I'm puzzled why. I confirmed it was added, but I'm still getting the migrations error. When will the patch be available via crates.io? I'm anxious to get my instance up and running. :)

`postgres=# \du`
`lemmy     | Superuser `

**Comment by Nutomic** [comment] 2023-06-14 13:48
That fix is not released yet, it will be in 0.18

**Comment by bengtfredh** [comment] 2023-06-15 20:23
@ffolkes I had same issue. Found out database server was missing postgresql extensions ltree and pgcrypto.

**Comment by ffolkes** [comment] 2023-06-16 06:59
> @ffolkes I had same issue. Found out database server was missing postgresql extensions ltree and pgcrypto.

Thank you! That did it. :) On Rocky 9 I needed to do "dnf install postgresql-contrib" and then "CREATE EXTENSION IF NOT EXISTS pgcrypto;" and "CREATE EXTENSION IF NOT EXISTS ltree;" then grant lemmy superuser to start it until the patch rolls out.

**Closed** 2023-06-26 11:20 UTC
Labels: bug

**Comment by DRKSLV** [comment] 2023-07-05 14:06
had trouble finding this since it was already closed

almost updated my postgres version oh no

thank you for the workaround!
